function money(n){return "₹"+n.toLocaleString("en-IN")}
function productCard(p){
  return `<article class="product-card"><a href="product.html?id=${p.id}" class="product-image ${p.bg}"><span class="product-emoji">${p.emoji}</span>${p.tags.includes("New")?'<label>NEW</label>':''}</a><div class="product-info"><div><a href="product.html?id=${p.id}"><h3>${p.name}</h3></a><p>${p.category}</p></div><strong>${money(p.price)}</strong></div></article>`;
}
function getCart(){try{return JSON.parse(localStorage.getItem("loremCart")||"[]")}catch(e){return[]}}
function saveCart(c){localStorage.setItem("loremCart",JSON.stringify(c));updateCartCount()}
function addToCart(id,qty=1){const c=getCart();const x=c.find(i=>i.id===id);if(x)x.qty+=qty;else c.push({id,qty});saveCart(c);showToast("Added to your bag ♡")}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll(".cart-count").forEach(x=>x.textContent=n)}
function showToast(t){let x=document.getElementById("toast");if(!x){x=document.createElement("div");x.id="toast";document.body.appendChild(x)}x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function setupSearch(){const btn=document.getElementById("searchBtn"),panel=document.getElementById("searchPanel"),input=document.getElementById("searchInput"),close=document.getElementById("closeSearch"),res=document.getElementById("searchResults");if(!btn)return;btn.onclick=()=>{panel.classList.add("open");input.focus()};close.onclick=()=>panel.classList.remove("open");input.oninput=()=>{const q=input.value.toLowerCase().trim();if(!q){res.innerHTML="";return}const matches=PRODUCTS.filter(p=>(p.name+" "+p.category).toLowerCase().includes(q)).slice(0,5);res.innerHTML=matches.length?matches.map(p=>`<a href="product.html?id=${p.id}">${p.name}<span>${money(p.price)}</span></a>`).join(""):"<p>No products found.</p>"}}
function setupMenu(){const b=document.getElementById("menuBtn"),n=document.querySelector("nav");if(b)b.onclick=()=>n.classList.toggle("open")}
document.addEventListener("DOMContentLoaded",()=>{updateCartCount();setupSearch();setupMenu();const np=document.getElementById("newProducts"),bp=document.getElementById("bestProducts");if(np)np.innerHTML=PRODUCTS.filter(p=>p.tags.includes("New")).slice(0,4).map(productCard).join("");if(bp)bp.innerHTML=PRODUCTS.filter(p=>p.tags.includes("Bestseller")).slice(0,4).map(productCard).join("");const f=document.getElementById("newsletterForm");if(f)f.onsubmit=e=>{e.preventDefault();document.getElementById("newsletterMsg").textContent="You're on the list ♡";f.reset()}});